theme: jekyll-theme-cayman
page.title: "＠フキダシアリス.anm"
twitter:
  username: tiribro
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /logo.jpg
        height: 630
        width: 1200
