theme: jekyll-theme-cayman
title: "フキダシアリス.anm"
description: "Aviutl拡張編集 アニメーション効果フィルター スクリプト"
twitter:
  username: tiribro
github:
  is_project_page: false
show_downloads: false
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
