theme: jekyll-theme-cayman
title: "フキダシアリス.anm"
description: "Aviutl拡張編集 アニメーション効果フィルター スクリプト"
show_downloads: false

twitter:
  username: tiribro

github:
  is_project_page: false
  zip_url: "https://github.com/tiribro/FukidashiALICE.anm/blob/master/%E3%83%95%E3%82%AD%E3%83%80%E3%82%B7%E3%82%A2%E3%83%AA%E3%82%B9.zip"

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
