theme: jekyll-theme-cayman
title: "フキダシアリス"
twitter:
  username: tiribro
site.github.is_project_page: 0
site.show_downloads: 0
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
