theme: jekyll-theme-cayman
title: "フキダシアリス.anm"
description: "Aviutl＆拡張編集 アニメーション効果フィルタ用スクリプト"
show_downloads: false

twitter:
  username: tiribro

github:
  is_project_page: false
  zip_url: "https://github.com/tiribro/FukidashiALICE.anm/releases/download/v0.0/FukidashiALICE.zip"

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
