theme: jekyll-theme-cayman
title: フキダシアリス.anm
twitter:
  username: tiribro
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
