theme: jekyll-theme-cayman
title: jekyllの利用方法
twitter:
  username: tiribro
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /logo.jpg
        height: 630
        width: 1200
